### PR TITLE
Starling V2 Webhook support

### PR DESCRIPTION
**Pull request by GazFranklin**

### CODE REVIEW

**Comment by scottrobertson** [comment]
Hey @GazFranklin 

Thanks for this.

I think we can get rid of the standing order endpoint, as you will end up with duplicate webhook events firing by supporting that.

**Comment by GazFranklin** [comment]
Yeah was gonna follow up actually - we (and users) only need to set up a Feed Item webhook. 

Feel free to use as much (or as little!) of it as you like haha

**Comment by GazFranklin** [comment]
Hey @scottrobertson 

Removed the redundant endpoint. 

FYI both my wife and I have been using this since mid-May now without issue. So sample size of 2, but better than nothing!

**Comment by scottrobertson** [comment]
> Hey @scottrobertson 
> 
> 
> 
> Removed the redundant endpoint. 
> 
> 
> 
> FYI both my wife and I have been using this since mid-May now without issue. So sample size of 2, but better than nothing!

Thank you :)

**Pull request merged**
